### ISSUE TITLE
e2fsprogs configure failure

### ISSUE THREAD

**Issue by watbulb** [daytonpid/FireHawk#1]
yocto autotools is having issues configuring e2fsprogs.

// Error 

configure.ac:830: error: possibly undefined macro: AC_CHECK_HEADERS

//Hypothesis

 autotools probably can't see certain m4 macros, specifically for pkg-config.

// Possible fix
1. Try adding pkg-config to build with priority before this recipe
2. If 1 fails, change contents of AC_CHECK_HEADERS env variable to a -l of custom aclocal from pkg-config.

**Comment by firepick1** [comment]
Yay test1!

On Monday, May 2, 2016, Dayton Pidhirney notifications@github.com wrote:

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/daytonpid/FireHawk/issues/1

## 

Karl Lew
FIREPICK SERVICES LLC
karl@firepick.org
www.firepick.org

**Comment by watbulb** [comment]
Closing issue, fixed in commit 45e38389984d3432845e77ee862cad19d6e700b7
